languageCode = 'en-us'
title = 'Axelerant Engineering Handbook'
theme = 'github.com/alex-shpak/hugo-book'
enableGitInfo = true
timeout = '10s'

[params]
    BookRepo = 'https://github.com/axelerant/engg-handbook'
    BookEditPath = 'edit/main'

[module]
[[module.imports]]
    path = 'github.com/alex-shpak/hugo-book'
